### ISSUE TITLE
[question] 有考慮輸出為 .ics 格式或餵給 Google Calendar 嗎?

### ISSUE THREAD

**Issue by vi9076** [TGmeetup/TGmeetup#15]
Hi, 如果輸出為 .ics 格式，就可以直接在行事曆軟體中直接使用，使用方式：
1. 儲存篩選條件 (1或多組，例如：conference, meetup-at-taipei, ...)
2. 讓程式自動定期更新資訊 (用 cron 或改為 daemon 方式)，依據各組篩選條件輸出至各自的 .ics 檔。
3. 在行事曆軟體中訂閱各 .ics 檔。

如果能餵給 Google Calendar 是最方便，不過會有點門檻:
- 像 Facebook 那樣，產生 webcal feed 讓 Google Calendar 來抓的話，使用者要自行架個 Internet 服務 https://steachs.com/archives/20286
- 程式裡呼叫 Google Calendar API 的話，好像也要搞 OAuth 那堆東西，有點麻煩。

**Comment by sufuf3** [comment]
Hi @vi9076 
Thank you for your suggestion.

您的建議很棒呢！
我也有想過將活動日期和時間加到 Google Calendar ，不過當時是想說大家有興趣的活動可以來加到自己的 Google Calendar。

不過這部分就如同您說的，會有一些複雜度。
所以在程式的設計與使用流程上，是需要再找時間來仔細規劃呢(是未來功能之一)～
不過依據您的建議有幾點考量

1. .ics 使用者需要自己在設定自動更新。在使用上可能會有一點的麻煩。甚至使用者還需要很勤勞的將 .ics 檔匯入。這邊考量到的會是希望寫出來的功能，大家會常使用到的。

2. webcal feed 是個很棒的方式，在 web 版出來後，會考慮在之後加這功能。(要使用者自己架 Internet 服務感覺有點勞煩 ^^)

3. 目前看起來是介接 Google Calendar API 是比較可行的方式。
如果是需要 OAuth 驗證，那就是在安裝的時候要有一步一步的指南來引導使用者，甚至也可以讓使用者選擇是否要開啟這項功能。
而這個實用性大，只要驗證一次，之後就可以一直使用。
大家如果忘記 web 版的網址，直接在 terminal 中使用，也比較方便。

如果有興趣的話，歡迎一起加入開發新功能的行列唷！ :) 
觀迎參考貢獻指南：https://github.com/TGmeetup/TGmeetup/blob/master/documents/CONTRIBUTING_zh-tw.md

**Comment by vi9076** [comment]
那看來依可行性來排序：

3.作為 API Client，適用一般個人/家庭網路環境。

2.需架設 Internet 服務，需有雲端 Server 或使用家中固網。
可以考慮加個 "Deploy to Heroku" 的按鈕，簡化步驟 (弱化架設能力?)
https://devcenter.heroku.com/articles/heroku-button

1.其實我沒長實間用過 .ics，一直以為檔案更新後，行事曆程式就會自動重讀 XD
那看來實用性有點低。
