### ISSUE TITLE
got SyntaxError as meetup list name

### ISSUE THREAD

**Issue by neighborhood999** [TGmeetup/TGmeetup#36]
Got `SyntaxError` as meetup list name on [tgmeetup.github.io](tgmeetup.github.io):

<img width="1277" alt="2018-08-20 11 06 38" src="https://user-images.githubusercontent.com/10325111/44318537-2c816900-a469-11e8-9373-5bf1e9db3793.png">

**Comment by neighborhood999** [comment]
@sufuf3 XDD, sorry my bad.

**Comment by sufuf3** [comment]
It's fine. Thanks for being interested in TGmeetup. :)
