### ISSUE TITLE
[Community/tw] Update Taipei-HashiCorp-User-Group

### ISSUE THREAD

**Issue by sufuf3** [TGmeetup/TGmeetup#62]
Add repository https://github.com/Taipei-HUG to https://github.com/TGmeetup/TGmeetup/blob/master/community/tw/Taipei-HashiCorp-User-Group/package.json
Ref: https://github.com/TGmeetup/TGmeetup/blob/master/documents/package.json.sample#L19-L22

**Comment by artslob** [comment]
Doing it
